apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
stringData:
  application-secret.yml: |
    jwt:
      expires-in: 86400 # 1day
      mobile-expires-in: 31536000
      tablet-expires-in: 31536000
      secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86G